// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yarzypjnfeevpqluyuxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhcnp5cGpuZmVldnBxbHV5dXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTMwMzEsImV4cCI6MjA2MzM2OTAzMX0.PjO-gJjC89EcbRT2ySKlESn1wqi3gcCQGqGpgrlEGDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);